// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTw7eWdIDqGq_oRa6WIo7ejK_EUkQuMyU',
    appId: '1:511834381303:web:bdb320e70ccb5c7678acf2',
    messagingSenderId: '511834381303',
    projectId: 'shuttleway-77262',
    authDomain: 'shuttleway-77262.firebaseapp.com',
    storageBucket: 'shuttleway-77262.firebasestorage.app',
    measurementId: 'G-VXWQV77BHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7X-sfB8oVVP0XkJcHFHGwwWhFRq4Y8Rw',
    appId: '1:511834381303:android:a12edfe0ddd393e278acf2',
    messagingSenderId: '511834381303',
    projectId: 'shuttleway-77262',
    storageBucket: 'shuttleway-77262.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs8o4POQeklnSoel3__Sf1ZStgp0Q1NoM',
    appId: '1:511834381303:ios:b7ca118f0ee2d62f78acf2',
    messagingSenderId: '511834381303',
    projectId: 'shuttleway-77262',
    storageBucket: 'shuttleway-77262.firebasestorage.app',
    androidClientId: '511834381303-iki4oguibon152qs12qrvfe5elkad8dp.apps.googleusercontent.com',
    iosClientId: '511834381303-hnfvab8beocf9q5cf2alcaknd74c6kup.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile',
  );
}
